language:
    - cpp

compiler:
    - g++

before_install:
    - sudo apt-get install gfortran
    - sudo apt-get install cmake
    - sudo apt-get install libopenblas-dev

script:
    - ./configure
    - make

